# Generated by Django 3.0.7 on 2020-08-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200729_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeRequestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(default=None, max_length=100, null=True)),
                ('jan', models.CharField(default=None, max_length=13, null=True)),
                ('get_matching_product_for_id_raw', models.TextField(null=True)),
                ('get_competitive_pricing_for_asin_raw', models.TextField(null=True)),
                ('get_lowest_offer_listings_for_asin_raw', models.TextField(null=True)),
                ('get_my_price_for_asin_raw', models.TextField(null=True)),
                ('get_product_categories_for_asin_raw', models.TextField(null=True)),
                ('scrape_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.ScrapeRequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
