REQUEST_STATUS_NEW = '1'
REQUEST_STATUS_IN_PROGRESS = '2'
REQUEST_STATUS_COMPLETED = '3'
REQUEST_STATUS_ERROR = '4'

REQUEST_STATUS = {
  REQUEST_STATUS_NEW: 'NEW',
  REQUEST_STATUS_IN_PROGRESS: 'IN_PROGRESS',
  REQUEST_STATUS_COMPLETED: 'COMPLETED',
  REQUEST_STATUS_ERROR: 'ERROR'
}

ID_ASIN = 'asin'
ID_JAN = 'jan'

ID_CHOICES = (
  (ID_ASIN, 'ASIN'),
  (ID_JAN, 'JAN')
)

## PAYPAL
PP_DEFAULT_PRODUCT_ID = 'AMZ-SCRP-SUBSCRIPTION'
