"""
Django settings for amazon_scraper project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g-d$qa$j(00$81-zz$jr(qelxncamz0+8hy5v(q1rjv6ojb*th'

# SECURITY WARNING: don't run with debug turned on in production!
ENV = environ.Env(
  DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
DEBUG = ENV("DEBUG")

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'main.User'
LOGIN_URL = 'main:login'
LOGIN_REDIRECT_URL = 'main:newrequest'
LOGOUT_REDIRECT_URL = 'main:login'

INSTALLED_APPS = [
    'livereload',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'api',
    'bootstrap4',
    'crispy_forms',
    'background_task',
    'rest_framework'
]
CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amazon_scraper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins':[ 
                'bootstrap4.templatetags.bootstrap4'
            ],
        },
    },
]

WSGI_APPLICATION = 'amazon_scraper.wsgi.application'

DATABASES = {
    'default': ENV.db()
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGGING = {
    'version': 1,   # これを設定しないと怒られる
    'disable_existing_loggers': False,
    'formatters': { # 出力フォーマットを文字列形式で指定する
        'all': {    # 出力フォーマットに`all`という名前をつける
            'format': '\t'.join([
                "[%(levelname)s]",
                "asctime:%(asctime)s",
                "module:%(module)s",
                "message:%(message)s",
            ])
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {  # ログをどこに出すかの設定
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'process_requests': { 
            'level': 'DEBUG',  # DEBUG以上のログを取り扱うという意味
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/process_requests.log'),
            'formatter': 'all',
            'maxBytes': 1024 * 1024,
            'backupCount': 2,
        }
    },
    'loggers': {  # どんなloggerがあるかを設定する
        'process_requests': { 
            'handlers': ['process_requests', 'console'],  # 先述のfile, consoleの設定で出力
            'level': 'DEBUG',
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR,'static') # 追加
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'main/static')
]
MEDIA_ROOT = os.path.join(BASE_DIR,'media') # 追加
MEDIA_URL = '/media/' # 追加

MAX_ATTEMPTS = 1

EMAIL_BACKEND = ENV('EMAIL_BACKEND')
DEFAULT_FROM_EMAIL = ENV('DEFAULT_FROM_EMAIL')
DEFAULT_CHARSET = ENV("DEFAULT_CHARSET")
EMAIL_HOST = ENV("EMAIL_HOST")
EMAIL_PORT = ENV("EMAIL_PORT")
EMAIL_HOST_USER = ENV("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = ENV("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = ENV("EMAIL_USE_TLS")

DJANGO_ENV=ENV("DJANGO_ENV")